FROM php:fpm
RUN docker-php-ext-install pdo_mysql
RUN apt-get update -y && apt-get install -y nginx supervisor
RUN rm -rf /etc/nginx/sites-*
RUN ln -sf /dev/stdout /var/log/nginx/access.log && ln -sf /dev/stderr /var/log/nginx/error.log
ADD ./conffiles/nginx-php.conf /etc/nginx/conf.d/nginx-php.conf
ADD ./conffiles/supervisor.conf /etc/supervisor.conf
ADD ./web/ /var/www/html/
EXPOSE 80
CMD ["supervisord", "-c", "/etc/supervisor.conf"]
